"""create_talon_reviews_table

Revision ID: da1114d8475c
Revises: 20260426_000003
Create Date: 2026-05-03 21:03:53.329054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'da1114d8475c'
down_revision: Union[str, Sequence[str], None] = '20260426_000003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talon_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('ocr_result_id', sa.Integer(), nullable=True),
    sa.Column('percepciones', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deducciones', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('liquido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tiene_programados', sa.Boolean(), nullable=False),
    sa.Column('monto_programados', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_70', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_70', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('liquidez_final', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('resultado', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ocr_result_id'], ['ocr_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talon_reviews_case_id'), 'talon_reviews', ['case_id'], unique=False)
    op.create_index(op.f('ix_talon_reviews_document_id'), 'talon_reviews', ['document_id'], unique=False)
    op.create_index(op.f('ix_talon_reviews_ocr_result_id'), 'talon_reviews', ['ocr_result_id'], unique=False)
    op.drop_index(op.f('ix_cases_seller_telegram'), table_name='cases')
    op.drop_constraint(op.f('uq_cases_public_id'), 'cases', type_='unique')
    op.create_index(op.f('ix_cases_public_id'), 'cases', ['public_id'], unique=True)
    op.create_index(op.f('ix_cases_seller_telegram_chat_id'), 'cases', ['seller_telegram_chat_id'], unique=False)
    op.drop_index(op.f('uq_documents_active_case_type'), table_name='documents', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_documents_active_case_type'), 'documents', ['case_id', 'document_type'], unique=True, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_cases_seller_telegram_chat_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_public_id'), table_name='cases')
    op.create_unique_constraint(op.f('uq_cases_public_id'), 'cases', ['public_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_cases_seller_telegram'), 'cases', ['seller_telegram_chat_id'], unique=False)
    op.drop_index(op.f('ix_talon_reviews_ocr_result_id'), table_name='talon_reviews')
    op.drop_index(op.f('ix_talon_reviews_document_id'), table_name='talon_reviews')
    op.drop_index(op.f('ix_talon_reviews_case_id'), table_name='talon_reviews')
    op.drop_table('talon_reviews')
    # ### end Alembic commands ###
