"""create_bot_chat_data

Revision ID: e232f501bee0
Revises: da1114d8475c
Create Date: 2026-05-10 14:17:24.915973
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e232f501bee0'
down_revision: Union[str, Sequence[str], None] = 'da1114d8475c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_chat_data',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_chat_data')
    # ### end Alembic commands ###
